title: Luke Mitchell 
logo: "/images/BeachCircle.png?raw=true" 
description: > 
  GIS Master's Certificate student at Portland State University
  <br />
  Computer Science Bacholor's from Oregon State University
  <br><br>
  <a href="https://www.linkedin.com/in/luke-mitchell-151b81202/">LinkedIn</a>
  <br />
  <a href="https://github.com/LukeMitchell-N">Github</a> 

  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
